default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    setup_ci

    match(
      type: "appstore",
      readonly: true,
      git_url: ENV["MATCH_GIT_URL"],
      git_basic_authorization: Base64.strict_encode64(ENV["MATCH_GIT_AUTH"])
    )

    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_method: "app-store",
      output_directory: "./build",
      output_name: "Runner.ipa"
    )

    upload_to_testflight(
      skip_waiting_for_build_processing: true,
      apple_id: ENV["APP_APPLE_ID"]
    )
  end
end
